package main

import (
	"strings"
	"testing"
)

// Reading a generated file back.
//
// Both sides of a refresh are rendered by Schema.Datasets, so a scan of one is
// a scan of the other and the only thing that can differ is what the warehouse
// said. That makes the scan the whole risk: every bug this file guards was a
// misread of the shape rather than a misread of the warehouse.

const generatedFile = `# Generated by "truegrain init" from the truegrain_demo dataset.
#
# Do not edit.

version: 0.2.0.dev0
semantic_model:
  - name: truegrain_demo
    datasets:
      - name: customers
        source: truegrain_demo.customers
        primary_key:
          - customer_id
        fields:
          - name: customer_id
            datatype: Integer
          - name: region
            datatype: String
      - name: orders
        source: truegrain_demo.orders
        primary_key:
          - order_id
        fields:
          - name: order_id
            datatype: Integer
    relationships:
      - name: orders_to_customers
        from: orders
        to: customers
        from_columns:
          - customer_id
`

func TestTheDatasetIsReadFromTheSourceNotTheComment(t *testing.T) {
	// A comment is prose and a source is what the engine reads, so only one of
	// them cannot drift. Refreshing the wrong dataset into a namespace would
	// be silent and very hard to see.
	if got := datasetOf(generatedFile); got != "truegrain_demo" {
		t.Errorf("datasetOf = %q, want truegrain_demo", got)
	}
	if got := datasetOf("nothing here"); got != "" {
		t.Errorf("a file with no source gave %q", got)
	}
	// A checkout on Windows must read the same as one on Linux.
	if got := datasetOf(strings.ReplaceAll(generatedFile, "\n", "\r\n")); got != "truegrain_demo" {
		t.Errorf("a CRLF checkout gave %q", got)
	}
}

// TestRelationshipsAreNotTables.
//
// They sit at the same indentation as datasets and their entries are also
// `- name:`, so a scan keyed on depth alone counted the joins. Adding one
// table with a foreign key then looked like two tables arriving, one of them
// with no columns at all.
func TestRelationshipsAreNotTables(t *testing.T) {
	tables := tablesIn(generatedFile)

	if len(tables) != 2 {
		t.Fatalf("read %d tables, want customers and orders: %v", len(tables), keysOf(tables))
	}
	if _, wrong := tables["orders_to_customers"]; wrong {
		t.Error("a relationship was read as a table")
	}
	if got := tables["customers"].columns; len(got) != 2 {
		t.Errorf("customers has columns %v, want two", got)
	}
}

// TestAnUnchangedTableSaysNothing.
//
// The report fires per file, so every table was compared on every run. Naming
// the ones that did not move buried the one that did, which on a dataset of
// any size is the whole report.
func TestAnUnchangedTableSaysNothing(t *testing.T) {
	tables := tablesIn(generatedFile)
	same := tablesIn(generatedFile)

	for name, before := range tables {
		if before.body != same[name].body {
			t.Errorf("%s read differently from an identical file", name)
		}
	}
}

// TestAColumnMovingIsVisibleInTheBody, which is what separates "a type or a
// key moved" from "nothing happened here" when the column names are equal.
func TestAColumnMovingIsVisibleInTheBody(t *testing.T) {
	retyped := strings.Replace(generatedFile,
		"          - name: region\n            datatype: String",
		"          - name: region\n            datatype: Integer", 1)

	before := tablesIn(generatedFile)["customers"]
	after := tablesIn(retyped)["customers"]

	if len(before.columns) != len(after.columns) {
		t.Fatal("the column names should not have changed")
	}
	if before.body == after.body {
		t.Error("a retyped column left the body identical, so the change would be reported as nothing")
	}
}

func TestAddedAndRemovedColumnsAreBothFound(t *testing.T) {
	added := strings.Replace(generatedFile,
		"          - name: region\n            datatype: String",
		"          - name: loyalty_tier\n            datatype: String", 1)

	before := tablesIn(generatedFile)["customers"].columns
	after := tablesIn(added)["customers"].columns

	if got := missing(after, before); len(got) != 1 || got[0] != "loyalty_tier" {
		t.Errorf("added = %v, want [loyalty_tier]", got)
	}
	// The one that breaks a query, so losing it would be the worse bug.
	if got := missing(before, after); len(got) != 1 || got[0] != "region" {
		t.Errorf("removed = %v, want [region]", got)
	}
}

func keysOf(m map[string]table) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	return out
}
