package introspect

import (
	"fmt"
	"strings"
)

// Turning what the warehouse said into a model somebody can read and edit.
//
// Two files, and the split between them is the point. The datasets are
// generated and carry a header saying so, because regenerating them after a
// schema change should be safe. The metrics file is written once and never
// touched again, because what revenue means is not derivable from a schema and
// a tool that guesses produces a catalogue nobody trusts.

// Ossie is the spec version this engine reads. Written into the generated file
// so a model carries the version it was written for.
const Ossie = "0.2.0.dev0"

// Datasets renders the generated half of the model.
func (s Schema) Datasets(namespace string) string {
	var b strings.Builder

	fmt.Fprintf(&b, `# Generated by "truegrain init" from the %s dataset.
#
# Do not edit. Every change here is overwritten the next time this is
# regenerated, and the warehouse is the source of truth for it.
#
# Metrics are deliberately absent: what revenue means is a business decision,
# not something derivable from a schema. Write them in metrics.yaml beside
# this file, which this command never touches.

version: %s
semantic_model:
  - name: %s
    datasets:
`, s.Name, Ossie, namespace)

	for _, t := range s.Tables {
		b.WriteString(dataset(s.Name, t))
	}

	if len(s.Relationships) > 0 {
		b.WriteString("    relationships:\n")
		for _, r := range s.Relationships {
			b.WriteString(relationship(r))
		}
	}
	return b.String()
}

func dataset(schema string, t Table) string {
	var b strings.Builder

	fmt.Fprintf(&b, "      - name: %s\n", t.Name)
	fmt.Fprintf(&b, "        source: %s.%s\n", schema, t.Name)

	if len(t.PrimaryKey) > 0 {
		b.WriteString("        primary_key:\n")
		for _, k := range t.PrimaryKey {
			fmt.Fprintf(&b, "          - %s\n", k)
		}
	} else {
		// Said in the file rather than only at the terminal, because the
		// terminal output scrolls away and this decides whether a fan-out
		// through this table can be detected at all.
		b.WriteString("        # No primary key is declared on this table, so its grain cannot be\n")
		b.WriteString("        # derived and a join through it cannot be checked for fan-out. Add\n")
		b.WriteString("        # primary_key here, or declare one on the table.\n")
	}

	if t.Description != "" {
		fmt.Fprintf(&b, "        description: %s\n", quote(t.Description))
	}

	b.WriteString("        fields:\n")
	for _, c := range t.Columns {
		fmt.Fprintf(&b, "          - name: %s\n", c.Name)
		b.WriteString("            expression:\n")
		b.WriteString("              dialects:\n")
		b.WriteString("                - dialect: ANSI_SQL\n")
		fmt.Fprintf(&b, "                  expression: %s\n", c.Name)
		fmt.Fprintf(&b, "            datatype: %s\n", ossieType(c.Type))
		if c.Description != "" {
			fmt.Fprintf(&b, "            description: %s\n", quote(c.Description))
		}
		b.WriteString("            dimension: {}\n")
	}
	return b.String()
}

func relationship(r Relationship) string {
	var b strings.Builder
	fmt.Fprintf(&b, "      - name: %s\n", r.Name)
	fmt.Fprintf(&b, "        from: %s\n", r.From)
	fmt.Fprintf(&b, "        to: %s\n", r.To)
	b.WriteString("        from_columns:\n")
	for _, c := range r.FromColumns {
		fmt.Fprintf(&b, "          - %s\n", c)
	}
	b.WriteString("        to_columns:\n")
	for _, c := range r.ToColumns {
		fmt.Fprintf(&b, "          - %s\n", c)
	}
	return b.String()
}

// MetricsFile renders the metrics half of the model.
//
// Two shapes, because the two sources are genuinely different. A warehouse
// schema declares no metrics, so `init` writes an empty file with a
// commented example built from a real column: the first edit is deleting a
// comment marker rather than inventing a shape from documentation. An
// importer reads metrics somebody already defined, and writing them out is
// the whole point of importing.
//
// Either way the file is written once and never regenerated. Overwriting
// somebody's metrics because they re-ran a setup command would be
// unforgivable.
func (s Schema) MetricsFile(namespace string) string {
	if len(s.Metrics) > 0 {
		return s.importedMetrics(namespace)
	}

	var b strings.Builder

	fmt.Fprintf(&b, `# Metrics for %s.
#
# Yours to write, and "truegrain init" will never overwrite this file.
#
# A schema can say an order has a total. Only a person can say that the number
# the business calls revenue is the sum of it over orders that were not
# cancelled. A tool that guesses produces a catalogue of plausible metrics
# nobody trusts, and an agent picking from it returns a wrong number with
# complete confidence.

version: %s
semantic_model:
  - name: %s
    metrics: []
`, namespace, Ossie, namespace)

	if example := exampleMetric(s); example != "" {
		b.WriteString("\n# Delete the `metrics: []` above and start from something like this:\n#\n")
		b.WriteString(example)
	}
	return b.String()
}

// exampleMetric builds a suggestion from a numeric column that actually
// exists, on a table that has a grain.
//
// Key columns are excluded, and not only the primary key. An integer foreign
// key is numeric and summing it is meaningless, so suggesting SUM(order_id) as
// somebody's first metric teaches the wrong thing on the first screen.
func exampleMetric(s Schema) string {
	joined := map[string]bool{}
	for _, r := range s.Relationships {
		for _, c := range r.FromColumns {
			joined[r.From+"."+c] = true
		}
		for _, c := range r.ToColumns {
			joined[r.To+"."+c] = true
		}
	}

	for _, t := range s.Tables {
		if len(t.PrimaryKey) == 0 {
			continue
		}
		for _, c := range t.Columns {
			if warehouseFamily(c.Type) != "number" || isKey(t, c.Name) || joined[t.Name+"."+c.Name] {
				continue
			}
			return fmt.Sprintf(`#     metrics:
#       - name: total_%s
#         description: >
#           Say what this means to the business, not what it does in SQL.
#           This description is how an agent decides whether to use it.
#         datatype: Number
#         expression:
#           dialects:
#             - dialect: ANSI_SQL
#               expression: SUM(%s.%s)
`, c.Name, t.Name, c.Name)
		}
	}
	return ""
}

func isKey(t Table, column string) bool {
	for _, k := range t.PrimaryKey {
		if strings.EqualFold(k, column) {
			return true
		}
	}
	return false
}

// Namespace renders the manifest, which is a decision rather than something
// derivable, so it is written once and says so.
func (s Schema) Namespace(namespace string) string {
	return fmt.Sprintf(`# The %s namespace.
#
# Yours to edit. Who owns these definitions and what they publish to other
# teams is a decision, not something a schema can answer, so this file is
# never regenerated.
#
# Replace the placeholder owner with the team that answers when one of these
# numbers is disputed. Everything is private unless listed under exports.

version: 1
name: %s
owners:
  - "@unassigned"
description: Generated from the %s dataset.
`, namespace, namespace, s.Name)
}

// ossieType maps a warehouse type onto the spec's vocabulary.
//
// Unrecognised types become String rather than being dropped: a field with no
// datatype accepts any scalar in a filter, which is a worse default than one
// that is merely imprecise, and the generated file is meant to be edited.
func ossieType(warehouse string) string {
	switch warehouseFamily(warehouse) {
	case "number":
		if strings.Contains(strings.ToUpper(warehouse), "INT") {
			return "Integer"
		}
		return "Decimal"
	case "date":
		return "Date"
	case "time":
		if strings.Contains(strings.ToUpper(warehouse), "TIMESTAMP") {
			return "DateTimeTz"
		}
		return "DateTime"
	case "boolean":
		return "Boolean"
	}
	return "String"
}

func warehouseFamily(t string) string {
	upper := strings.ToUpper(strings.TrimSpace(t))
	switch {
	case upper == "DATE":
		return "date"
	case strings.Contains(upper, "TIMESTAMP"), strings.Contains(upper, "DATETIME"), upper == "TIME":
		return "time"
	case upper == "BOOL", upper == "BOOLEAN":
		return "boolean"
	case strings.Contains(upper, "INT"), strings.Contains(upper, "NUMERIC"),
		strings.Contains(upper, "DECIMAL"), strings.Contains(upper, "BIGNUMERIC"),
		strings.Contains(upper, "FLOAT"), strings.Contains(upper, "DOUBLE"):
		return "number"
	case strings.Contains(upper, "CHAR"), strings.Contains(upper, "STRING"), upper == "TEXT":
		return "text"
	}
	return ""
}

// quote renders a description safely into YAML.
//
// Warehouse descriptions are written by whoever created the table and contain
// colons, quotes and newlines often enough that emitting them bare produces a
// file that will not parse, which is a bad first impression for a command
// whose entire job is producing a file that does.
func quote(s string) string {
	s = strings.Map(func(r rune) rune {
		if r == '\n' || r == '\r' || r == '\t' {
			return ' '
		}
		if r < 0x20 {
			return -1
		}
		return r
	}, s)
	return `"` + strings.ReplaceAll(strings.ReplaceAll(s, `\`, `\\`), `"`, `\"`) + `"`
}

// importedMetrics renders metrics a source already defined.
//
// Written as ANSI_SQL, which is what every dialect emitter reads and
// rewrites for its own warehouse. An importer that emitted the source
// warehouse's spelling would produce a model that only runs where it came
// from, which would defeat the point of importing it.
func (s Schema) importedMetrics(namespace string) string {
	var b strings.Builder

	fmt.Fprintf(&b, `# Metrics for %s, imported.
#
# Yours now. This file is written once and never regenerated, so editing it
# is safe and re-running the importer will not overwrite your changes.
#
# Read them before trusting them. An importer carries across what the source
# declared, and the source may have been wrong; what this engine adds is
# that a question these cannot answer correctly is now refused rather than
# answered with an inflated number.

version: %s
semantic_model:
  - name: %s
    metrics:
`, namespace, Ossie, namespace)

	for _, m := range s.Metrics {
		fmt.Fprintf(&b, "      - name: %s\n", m.Name)
		fmt.Fprintf(&b, "        description: %s\n", quote(describeMetric(m)))
		datatype := m.Datatype
		if datatype == "" {
			datatype = "Number"
		}
		fmt.Fprintf(&b, "        datatype: %s\n", datatype)
		b.WriteString("        expression:\n")
		b.WriteString("          dialects:\n")
		b.WriteString("            - dialect: ANSI_SQL\n")
		fmt.Fprintf(&b, "              expression: %s\n", m.Expression)
	}
	return b.String()
}

// describeMetric supplies a description when the source had none.
//
// validate requires one, for a good reason: an agent reads it to decide
// whether a metric answers the question, and an undescribed metric gets
// picked wrongly or not at all. Without this an imported model would fail
// validation on its first run, which is a bad first minute.
//
// The placeholder says what it is rather than inventing a meaning. Writing
// "Total revenue" from a metric called total_revenue would be a description
// that reads as considered and says nothing, which is worse than one that
// admits it is a placeholder: a person can grep for it, and an agent
// reading it learns not to trust the metric rather than trusting a
// tautology.
func describeMetric(m Metric) string {
	if m.Description != "" {
		return m.Description
	}
	return "TODO: imported without a description. Say what this means to the " +
		"business, not what it does in SQL; an agent reads this to decide " +
		"whether the metric answers a question."
}

// MetricsNeedingDescription counts the imported metrics carrying a
// placeholder, so an importer reports the number rather than leaving it to
// be discovered one validate at a time.
func (s Schema) MetricsNeedingDescription() int {
	n := 0
	for _, m := range s.Metrics {
		if m.Description == "" {
			n++
		}
	}
	return n
}
